wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1654679271
    t:
      3:
      - 2
      - 13
      4: 3.7.11
      5: 0.12.10
      8:
      - 8
