data:
  template: ${oc.env:DATA_ROOT}/linear/template.png
  moving: ${oc.env:DATA_ROOT}/linear/moving.png
  dir: ${oc.env:DATA_ROOT}/linear
  iterations:
    20.0:
      max_iter: -1
      max_bad: 10
    10.0:
      max_iter: -1
      max_bad: 10
    5.0:
      max_iter: -1
      max_bad: 10
    2.0:
      max_iter: -1
      max_bad: 10
    1.0:
      max_iter: 1
      max_bad: 10
  scale: 1
  preprocessing:
    _target_: src.common.preprocessing.linear
logging:
  debug: false
  wandb:
    entity: privacy-ai
    mode: online
metric:
  _target_: src.metrics.ssd.SSD
model:
  _target_: src.models.affine.Affine
joint_computation:
  _target_: src.joint_computations.clear.Clear
  name: clear
register:
  _target_: src.registers.urs_register.URSRegister
  percent_pixels: 5
  max_bad: 10
  max_iter: 1
  name: urs
sampler:
  _target_: src.samplers.spline.Spline
core:
  name: run_0
