# metadata specialised for each experiment
core:
  name: run_0

defaults:
  - data: linear
  - hydra: default
  - logging: wandb
  - metric: ssd
  - model: affine
  - joint_computation: clear
  - register: base
  - sampler: spline